// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.

export const environment = {
  production: false,
  version: '1.0' + '-dev',
  serverUrl: '/',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'de-DE', 'fr-FR'],
  applicationName: 'TMS',
  clientId: 'AE7F6859-6851-4A13-9214-E8D49634E32D',
  clientSecret: '470E67DE-BEFB-4487-888D-20C37883B56E',
  SSOURL: 'https://ims.dev.na.baps.org/sso-v2local/',
  redirectUri: 'http://localhost:4200/auth/callback'
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
